myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:  # 主要目的是给上级类添加一些功能，或者指定一些标准
        ordering = ('-publish',)

    def __str__(self):  # 得到想要的易于人阅读的对象的信息
        return self.title

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, 'blog/titles.html', {'blogs': blogs})


def blog_article(request, article_id):
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, 'blog/content.html', {'article': article, 'publish': pub})

myblog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-cn">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=devce-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% include "foot.html" %}
        {% block javascript %}{% endblock %}
    </body>
</html>

myblog/templates/blog/content.html
{% extends "base.html" %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

{% load static %}

<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-centre"><span>{{ article.author.username }}
        </span><span style="margin-left:20px">{{ publish }}</span>
        </p>
        <div>{{ article.body }}</div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h3>欢迎互相学习交流</h3>
        <p>Email:wilburzzz@qq.com</p>
        <img src="{% static '/images/mouse.jpg' %}" width="100px">
    </div>
</div>
{% endblock %}

myblog/templates/blog/titles.html
{% extends "base.html" %}

{% block title %}HomePage{% endblock %}

{% block content %}

{% load static %}

<div class="row text-center vertical-middle-sm">
    <h2>Wellcome To My BLOG</h2>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
    <ul>
    {% for blog in blogs %}
        <li><a href="{{ blog.id }}">{{ blog.publish }}<br>{{ blog.title }}</a></li>
        <br>
    {% endfor %}
    </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h3>欢迎互相学习交流</h3>
        <p>Email:wilburzzz@qq.com</p>
        <img src="{% static '/images/mouse.jpg' %}" width="100px">
    </div>
</div>
{% endblock %}

myblog/templates/foot.html
{% load static %}
<div class="container"> <hr>
    <p class="text-center"><img src="{% static '/images/logo.jpg' %}" width="60px"> @ copy right WilburZ </p>
</div>

myblog/templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'blog:blog_title' %}">
                <img src="{% static '/images/logo.jpg' %}" width="60px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">HOME</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                <li><a href="#">LOGIN</a></li>
                <li><a href="#">Sign up</a></li>
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>